// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJ1scX8js63VXvJNojWV2sn1ac-_dqPg',
    appId: '1:378878373707:web:775c5e8cd6d40a8e8942ce',
    messagingSenderId: '378878373707',
    projectId: 'bigqazaq-30ff2',
    authDomain: 'bigqazaq-30ff2.firebaseapp.com',
    storageBucket: 'bigqazaq-30ff2.appspot.com',
    measurementId: 'G-00FYTTGNNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSz7pngsaM3U1BOf7KHQPfoOXeJczDqgs',
    appId: '1:378878373707:android:3af2808a08d468f38942ce',
    messagingSenderId: '378878373707',
    projectId: 'bigqazaq-30ff2',
    storageBucket: 'bigqazaq-30ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7prFeoj1SlX-3_NP79Ou0VKo4Jtd5vk',
    appId: '1:378878373707:ios:fabdcb787822d4148942ce',
    messagingSenderId: '378878373707',
    projectId: 'bigqazaq-30ff2',
    storageBucket: 'bigqazaq-30ff2.appspot.com',
    iosBundleId: 'com.example.bigQazaqApp',
  );
}
